### ISSUE TITLE
[Broken] Downloading all YT playlists no longer works

### ISSUE THREAD

**Issue by Filippilny** [blackjack4494/yt-dlc#93] opened 2020-11-01 10:44 UTC
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

```
youtube-dlc -v -f 'bestvideo+bestaudio' 'https://www.youtube.com/c/austinevans/playlists' 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo+bestaudio', 'https://www.youtube.com/c/austinevans/playlists']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.10.31
[debug] Python version 3.8.6 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube:playlists] austinevans: Downloading webpage
[download] Downloading playlist: Austin Evans
[youtube:playlists] playlist Austin Evans: Downloading 0 videos
[download] Finished downloading playlist: Austin Evans

```

Hey, this seems to be broken for a few days (weeks?) now. The command as is should download all videos from all playlists on given channel. I mainly use it for downloading my playlists, but for simplification I stripped the command to just basic stuff and tried a public channel. I also tried the OG yt-dl, where it also doesn't work, so I guess this is some change on Youtube's side.

**Comment by etec-masterofsynapse** [comment] 2020-11-01 12:46
Doesnt calling ytdlc with the channel URL do exactly that? I didnt try running it on a channel with multiple playlists across many channels yet but if I want to archive a channel with all its videos this does do the job.

**Comment by Filippilny** [comment] 2020-11-01 13:29
Well, lets say that I call "youtube-dlc -v -o '%(playlist)s/%(title)s.%(ext)s' -f 'bestvideo+bestaudio' --yes-playlist 'https://www.youtube.com/c/austinevans/'. This should (and it was working before) create a seperate folder for every playlist. But since I am pointing it to the channel, not the chanel's playlists, it downloads all uploads of the channel and puts them in one folder. And I don't want all uploads, I only want the playlists.

**Comment by etec-masterofsynapse** [comment] 2020-11-01 13:38
Ok, your requirement is for channels, that didnt put all their videos into playlists, but rather leave some out.
Or else downloading all uploads would accomplish the same.
And it seems like the /playlists page puts out something different that ytdl(c) isnt able to work with yet.
So its a change from YT.

**Comment by Filippilny** [comment] 2020-11-01 14:14
Yes, thats basically it. I dont care about all uploads, I just want the playlists.

**Comment by tygore587** [comment] 2020-11-04 07:58
I also came accross this problem. It breaks my backup strategy for some channels.

**Comment by tygore587** [comment] 2020-11-04 07:58
I also came accross this issue.

**Comment by humor4fun** [comment] 2020-11-06 16:48
I've run into this as well. I use a bulk list file and many of my entries are in the format

> youtube.com/playlist?list=id

Examples:
> https://www.youtube.com/playlist?list=PLrwRJhfJmJRjDYmKTU9DY7XsG09QOBhwl
> https://www.youtube.com/playlist?list=PLrwRJhfJmJRieuLL2duvz4LlAZ6Zr3FLg

**Comment by ZenulAbidin** [comment] 2020-11-09 13:04
I have a fix for this bug pending on another repo:

https://github.com/l1ving/youtube-dl/pull/32

The regexes that match the Load more key and the playlist IDs were broken that’s all.

I will make a PR for this here shortly.

**Comment by blackjack4494** [comment] 2020-11-09 13:40
> I have a fix for this bug pending on another repo:
> 
> [l1ving/youtube-dl#32](https://github.com/l1ving/youtube-dl/pull/32)
> 
> The regexes that match the Load more key and the playlist IDs were broken that’s all.
> 
> I will make a PR for this here shortly.

Haven't looked into it but I assume it's using the new endpoint youtube is using so it should give you some json response.

**Closed** 2020-11-10 21:58 UTC

**Comment by tygore587** [comment] 2020-11-10 22:08
@blackjack4494 I just installed the master branch with pip and the problem is not fixed. 

It now finds playlist for the link, but no videos in the playlists itself.

Example:
```
youtube-dlc --yes-playlist https://www.youtube.com/channel/UC46xhU1EH7aywEgvA9syS3w/playlists
[youtube:playlists] UC46xhU1EH7aywEgvA9syS3w: Downloading webpage
[download] Downloading playlist: anthonywritescode
[youtube:playlists] playlist anthonywritescode: Downloading 8 videos
[download] Downloading video 1 of 8
[youtube:playlist] PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY
[youtube:playlist] playlist PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY
[download] Downloading video 2 of 8
[youtube:playlist] PLWBKAf81pmObN-y79Z8rmxTereowh9ZXn: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmObN-y79Z8rmxTereowh9ZXn
[youtube:playlist] playlist PLWBKAf81pmObN-y79Z8rmxTereowh9ZXn: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmObN-y79Z8rmxTereowh9ZXn
[download] Downloading video 3 of 8
[youtube:playlist] PLWBKAf81pmOZEPeIV2_pIESK5hRMAo1hR: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOZEPeIV2_pIESK5hRMAo1hR
[youtube:playlist] playlist PLWBKAf81pmOZEPeIV2_pIESK5hRMAo1hR: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOZEPeIV2_pIESK5hRMAo1hR
[download] Downloading video 4 of 8
[youtube:playlist] PLWBKAf81pmOZuuQiuOT4Ag-yeTfZ9cN3_: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOZuuQiuOT4Ag-yeTfZ9cN3_
[youtube:playlist] playlist PLWBKAf81pmOZuuQiuOT4Ag-yeTfZ9cN3_: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOZuuQiuOT4Ag-yeTfZ9cN3_
[download] Downloading video 5 of 8
[youtube:playlist] PLWBKAf81pmObOrW-9Rcq9ZIzFkE7WQUqW: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmObOrW-9Rcq9ZIzFkE7WQUqW
[youtube:playlist] playlist PLWBKAf81pmObOrW-9Rcq9ZIzFkE7WQUqW: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmObOrW-9Rcq9ZIzFkE7WQUqW
[download] Downloading video 6 of 8
[youtube:playlist] PLWBKAf81pmOamJfoHz4oRdieWQysmUkaW: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOamJfoHz4oRdieWQysmUkaW
[youtube:playlist] playlist PLWBKAf81pmOamJfoHz4oRdieWQysmUkaW: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOamJfoHz4oRdieWQysmUkaW
[download] Downloading video 7 of 8
[youtube:playlist] PLWBKAf81pmOY7f7YZg_aEvkyiLdbmOhHW: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOY7f7YZg_aEvkyiLdbmOhHW
[youtube:playlist] playlist PLWBKAf81pmOY7f7YZg_aEvkyiLdbmOhHW: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOY7f7YZg_aEvkyiLdbmOhHW
[download] Downloading video 8 of 8
[youtube:playlist] PLWBKAf81pmOZOukFi2KyQJ7QMNDzcq2yT: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOZOukFi2KyQJ7QMNDzcq2yT
[youtube:playlist] playlist PLWBKAf81pmOZOukFi2KyQJ7QMNDzcq2yT: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOZOukFi2KyQJ7QMNDzcq2yT
[download] Finished downloading playlist: anthonywritescode
```

**Comment by tygore587** [comment] 2020-11-10 22:14
@blackjack4494 Hey i just installed the lastest version from master with `python -m pip install git+https://github.com/blackjack4494/yt-dlc` 

It now finds playlists again for /playlists links, but it is not finding videos in the playlists on this page.

Example output for: `youtube-dlc --yes-playlist https://www.youtube.com/channel/UC46xhU1EH7aywEgvA9syS3w/playlists`
```
▶ youtube-dlc --yes-playlist https://www.youtube.com/channel/UC46xhU1EH7aywEgvA9syS3w/playlists
[youtube:playlists] UC46xhU1EH7aywEgvA9syS3w: Downloading webpage
[download] Downloading playlist: anthonywritescode
[youtube:playlists] playlist anthonywritescode: Downloading 8 videos
[download] Downloading video 1 of 8
[youtube:playlist] PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY
[youtube:playlist] playlist PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY
[download] Downloading video 2 of 8
[youtube:playlist] PLWBKAf81pmObN-y79Z8rmxTereowh9ZXn: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmObN-y79Z8rmxTereowh9ZXn
[youtube:playlist] playlist PLWBKAf81pmObN-y79Z8rmxTereowh9ZXn: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmObN-y79Z8rmxTereowh9ZXn
[download] Downloading video 3 of 8
[youtube:playlist] PLWBKAf81pmOZEPeIV2_pIESK5hRMAo1hR: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOZEPeIV2_pIESK5hRMAo1hR
[youtube:playlist] playlist PLWBKAf81pmOZEPeIV2_pIESK5hRMAo1hR: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOZEPeIV2_pIESK5hRMAo1hR
[download] Downloading video 4 of 8
[youtube:playlist] PLWBKAf81pmOZuuQiuOT4Ag-yeTfZ9cN3_: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOZuuQiuOT4Ag-yeTfZ9cN3_
[youtube:playlist] playlist PLWBKAf81pmOZuuQiuOT4Ag-yeTfZ9cN3_: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOZuuQiuOT4Ag-yeTfZ9cN3_
[download] Downloading video 5 of 8
[youtube:playlist] PLWBKAf81pmObOrW-9Rcq9ZIzFkE7WQUqW: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmObOrW-9Rcq9ZIzFkE7WQUqW
[youtube:playlist] playlist PLWBKAf81pmObOrW-9Rcq9ZIzFkE7WQUqW: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmObOrW-9Rcq9ZIzFkE7WQUqW
[download] Downloading video 6 of 8
[youtube:playlist] PLWBKAf81pmOamJfoHz4oRdieWQysmUkaW: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOamJfoHz4oRdieWQysmUkaW
[youtube:playlist] playlist PLWBKAf81pmOamJfoHz4oRdieWQysmUkaW: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOamJfoHz4oRdieWQysmUkaW
[download] Downloading video 7 of 8
[youtube:playlist] PLWBKAf81pmOY7f7YZg_aEvkyiLdbmOhHW: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOY7f7YZg_aEvkyiLdbmOhHW
[youtube:playlist] playlist PLWBKAf81pmOY7f7YZg_aEvkyiLdbmOhHW: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOY7f7YZg_aEvkyiLdbmOhHW
[download] Downloading video 8 of 8
[youtube:playlist] PLWBKAf81pmOZOukFi2KyQJ7QMNDzcq2yT: Downloading webpage
[download] Downloading playlist: PLWBKAf81pmOZOukFi2KyQJ7QMNDzcq2yT
[youtube:playlist] playlist PLWBKAf81pmOZOukFi2KyQJ7QMNDzcq2yT: Downloading 0 videos
[download] Finished downloading playlist: PLWBKAf81pmOZOukFi2KyQJ7QMNDzcq2yT
[download] Finished downloading playlist: anthonywritescode
```

**Comment by Filippilny** [comment] 2020-11-10 23:41
Well, it looks like the PR fixed some issues, but introduced many more. For example, no videos now pass the match filter, only first 100 videos in every playlist are considered. Also, it now doesn't recognize / name corretly the playlists, it is some ?random? string of characters. Can please someone reopen this issue? Thanks

**Comment by humor4fun** [comment] 2020-11-10 23:45
I concur, none of my playlists are recognized to have any videos in them at all now.

```
[youtube:playlists] playlist Bsides Warsaw: Downloading 0 videos
[download] Finished downloading playlist: Bsides Warsaw
[youtube:playlists] irongeek: Downloading webpage
[download] Downloading playlist: Adrian Crenshaw
[youtube:playlists] playlist Adrian Crenshaw: Downloading 0 videos
[download] Finished downloading playlist: Adrian Crenshaw
[youtube:playlists] UCNQOGXlvuAhv4b1MRrv4TGQ: Downloading webpage
[download] Downloading playlist: The Long Con
[youtube:playlists] playlist The Long Con: Downloading 0 videos
[download] Finished downloading playlist: The Long Con
[youtube:playlists] OWASPGLOBAL: Downloading webpage
[download] Downloading playlist: OWASP
[youtube:playlists] playlist OWASP: Downloading 0 videos
[download] Finished downloading playlist: OWASP
[youtube:playlists] mediacccde: Downloading webpage
[download] Downloading playlist: media.ccc.de
[youtube:playlists] playlist media.ccc.de: Downloading 0 videos
```
