### ISSUE TITLE
[Broken] "Unable to extract video data" when using cookies on YouTube

### ISSUE THREAD

**Issue by ALXMRW** [blackjack4494/yt-dlc#37] opened 2020-10-28 03:36 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\youtube-dlc>youtube-dlc -v --cookies cookies.txt https://www.youtube.com/watch?v=JR4KHfqw-oE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'https://www.youtube.com/watch?v=JR4KHfqw-oE']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.26
[debug] Python version 3.8.6 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] JR4KHfqw-oE: Downloading webpage
ERROR: JR4KHfqw-oE: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\youtube.py", line 1865, in _real_extract
youtube_dlc.utils.ExtractorError: JR4KHfqw-oE: YouTube said: Unable to extract video data
```

## Description

As of October 20th, using `--cookies` no longer works correctly with my YouTube account. No matter if the video is public or members-only, I still get the same error. While I can just omit this option to download public videos, this becomes a problem when I want to download members-only videos. Between the time of it working and not working, nothing with my setup was changed in any way which leads me to believe this is something YouTube changed on the back-end.

I have signed out and back in to YouTube multiple times, have generated new cookies files multiple times, even tried on another machine but still receive the same error. There was another user who submitted this exact issue back on the old repository but unfortunately I didn't think to make an archive to use for reference.

What adds to the frustration is that this only seems to be happening selectively. When asked, most have reported no recent problems while a few users I've found online seem to have the exact issue as described here.

**Comment by october262** [comment] 2020-10-28 04:14
try using  youtube-dlc --force-generic-extractor https://www.youtube.com/watch?v=JR4KHfqw-oE
--cookies  cookies.txt file
try using cookies on a age gated video such as this one - https://www.youtube.com/watch?v=XgnwCQzjau8

**Comment by ALXMRW** [comment] 2020-10-28 04:27
Same error on both attempts. As long as `--cookies` is used, I get that error.

**Comment by october262** [comment] 2020-10-28 04:55
> Same error on both attempts. As long as `--cookies` is used, I get that error.

i was able to download your link without using cookies.
the second link i posted requires cookies to be used which worked for me.
might try running running  python3 youtube-dlc   https://www.youtube.com/watch?v=XgnwCQzjau8  --cookies  cookies.txt file make sure that you are signed in when trying this

**Comment by ALXMRW** [comment] 2020-10-28 05:45
> i was able to download your link without using cookies.

As stated in my first post, downloading any public and non-age-gated videos—with or without `--force-generic-extractor`—work fine. As soon as `--cookies` is used, I get the error.

> might try running running python3 youtube-dlc https://www.youtube.com/watch?v=XgnwCQzjau8 --cookies cookies.txt file make sure that you are signed in when trying this

Unfortunately, I'm very unfamiliar with Python so I don't know how to get it working to test that out.

**Comment by someziggyman** [comment] 2020-10-28 09:10
I can confirm there's some problem using cookies for videos that require it.
Test link used: https://www.youtube.com/watch?v=XgnwCQzjau8

Link reported by ALXMRW initially is working fine for me both with and without cookies:
https://www.youtube.com/watch?v=JR4KHfqw-oE

**Error output log:**
./testdlc -v --cookie cookfile.txt -F https://www.youtube.com/watch?v=XgnwCQzjau8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--cookie', u'cookfile.txt', u'-F', u'https://www.youtube.com/watch?v=XgnwCQzjau8']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.25
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] XgnwCQzjau8: Downloading webpage
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./testdlc/__main__.py", line 19, in <module>
  File "./testdlc/youtube_dlc/__init__.py", line 487, in main
  File "./testdlc/youtube_dlc/__init__.py", line 477, in _real_main
  File "./testdlc/youtube_dlc/YoutubeDL.py", line 2096, in download
  File "./testdlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
  File "./testdlc/youtube_dlc/extractor/common.py", line 532, in extract
  File "./testdlc/youtube_dlc/extractor/youtube.py", line 1759, in _real_extract
  File "./testdlc/youtube_dlc/extractor/common.py", line 2866, in _get_cookies
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'

**Comment by BlohoJo** [comment] 2020-10-29 07:25
Try deleting your C:\Users\[USER-ID]\.cache folder. That's created and used by youtube-dl.

It's usually a good idea to always take this step when doing preliminary troubleshooting.

**Comment by ALXMRW** [comment] 2020-10-29 18:59
> Try deleting your `C:\Users\[USER_ID]\.cache` folder. This folder is created and used by youtube-dl.

Thanks for tipping me off to that. Unfortunately, wiping it didn't make any difference and the error still persists.

**Comment by blackjack4494** [comment] 2020-10-31 08:31
Maybe try this extension for chrome
https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en

Will close this for now since everything is working fine for me.
Try newest release :P

**Closed by blackjack4494** 2020-10-31 08:31 UTC
