### ISSUE TITLE
youtube channel page downloads broken

### ISSUE THREAD

**Issue by bani6809** [blackjack4494/yt-dlc#148] opened 2020-11-09 20:24 UTC
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dlc version **2020.10.31**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
youtube-dlc.exe --ignore-config -i -o "%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s" --prefer-ffmpeg --merge-output-format mkv --write-sub --all-subs --convert-subs srt --add-metadata --write-description --write-annotations --write-all-thumbnails --write-info-json --cookies youtube-cookies.txt -v --proxy "" https://www.youtube.com/channel/UC7qPftDWPw9XuExpSgfkmJQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-i', '-o', '%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '--write-sub', '--all-subs', '--convert-subs', 'srt', '--add-metadata', '--write-description', '--write-annotations', '--write-all-thumbnails', '--write-info-json', '--cookies', 'youtube-cookies.txt', '-v', '--proxy', '', 'https://www.youtube.com/channel/UC7qPftDWPw9XuExpSgfkmJQ']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.07
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-04-24-a501947, ffprobe git-2020-04-24-a501947
[debug] Proxy map: {}
[youtube:channel] UC7qPftDWPw9XuExpSgfkmJQ: Downloading channel page
[youtube:playlist] UU7qPftDWPw9XuExpSgfkmJQ: Downloading webpage
[download] Downloading playlist: UU7qPftDWPw9XuExpSgfkmJQ
[youtube:playlist] playlist UU7qPftDWPw9XuExpSgfkmJQ: Downloading 0 videos
[download] Finished downloading playlist: UU7qPftDWPw9XuExpSgfkmJQ

```

## Description

youtube playlist downloads seem to have broken sometime within the last few hours. it was working earlier this morning, now all playlists result in "0 videos" from youtube-dlc. presumably youtube made a schema change which broke youtube-dlc.

Individual video downloads still work, for example this works perfectly:

youtube-dlc.exe --ignore-config -i -o "%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s" --prefer-ffmpeg --merge-output-format mkv --write-sub --all-subs --convert-subs srt --add-metadata --write-description --write-annotations --write-all-thumbnails --write-info-json --cookies youtube-cookies.txt -v --proxy "" https://www.youtube.com/watch?v=SXGAiTjFiMA

**Comment by someziggyman** [comment] 2020-11-09 21:25
@insaneracist @blackjack4494 
I can confirm that this is broken for links like:
https://www.youtube.com/user/anjunadeep/videos
and "regular" playlists like this ID: PLOftnzGIKwJAfH33eTU2wDsBqwxOMRedV
Full link: https://www.youtube.com/watch?v=mhpfOQ6sf3s&list=PLOftnzGIKwJAfH33eTU2wDsBqwxOMRedV

**Mix, search and user created playlists seem to be working just fine:**
mix id to test: RDKR9wGi7gVLQ
search playlist to test: https://www.youtube.com/results?search_query=linkin+park+numb

**Comment by bani6809** [comment] 2020-11-09 21:59
seems widely confirmed: https://www.reddit.com/r/youtubedl/comments/jr56fs/yourubedl_sees_all_channel_links_as_empty/

**Comment by ainsey11** [comment] 2020-11-09 22:08
I too am seeing this issue, looks to be a global thing, same problem wherever I initiate the download from

**Comment by ainsey11** [comment] 2020-11-09 22:38
It would appear that youtube has disabled the "disable_polymer" feature that the YT extractor requires, 

When visiting a playlist with the flag set, I now get unknown param

![image](https://user-images.githubusercontent.com/6608275/98604722-22631380-22dc-11eb-9474-95b732d91936.png)

I can see the extractor is doing `
```python
        query['disable_polymer'] = 'true'

```
so that is my hunch

**Comment by jbruchon** [comment] 2020-11-09 23:36
@ainsey11 I can second what you've found there. Seems you're on the right track.

**Comment by etec-masterofsynapse** [comment] 2020-11-10 00:38
Sorry if its a dumb question: Why does the extractor need the "old theme / non-polymer"?
Is it not currently able to pull the video IDs from the new theme?

**Comment by wlritchi** [comment] 2020-11-10 01:21
> Sorry if its a dumb question: Why does the extractor need the "old theme / non-polymer"?
> Is it not currently able to pull the video IDs from the new theme?

The extractor currently looks for HTML markup for each entry in a playlist. When the polymer frontend was introduced, YouTube changed from server-side rendering of HTML templates to client-side rendering. As a result, the HTML source received from the server no longer contains the markup the extractor looks for, and the only place that playlist items appear is in a JSON structure (and a fairly dense one at that). Now that the extractor can no longer opt out of polymer, it will need to be updated to pull data out of that structure.

**Comment by ZenulAbidin** [comment] 2020-11-10 02:25
It seems to be failing at youtube_dlc/extractor/youtube.py:_extract_playlist

https://github.com/blackjack4494/yt-dlc/blob/master/youtube_dlc/extractor/youtube.py#L2890-L2892

Every match after these lines isn't working.

**Comment by candrapersada** [comment] 2020-11-10 04:51
> Individual video downloads still work, for example this works perfectly

how to use playlist track number from Individual video downloads?

**Comment by jbruchon** [comment] 2020-11-10 05:40
@candrapersada That's fine as a hack, but for all of us who do archival, it's a really bad hack to put in place. Using that method, there is no way to scan the archive for all of the playlist items and avoid downloading the page for every single one of those items. I archive over 150 channels regularly and dropping down to this method would be a little bit of a disaster.

**Comment by jbruchon** [comment] 2020-11-10 05:42
If no one has taken up the task of getting this fixed yet, I might give it a try tomorrow.

**Comment by blackjack4494** [comment] 2020-11-10 06:12
Check network tab in browser. They likely completely changed over to api usage returning json instead of html events

**Comment by candrapersada** [comment] 2020-11-10 06:33
what I mean is how to want youtube-dlc to name the files like 1-{name}, 2-{name}, ... n-{name} in order to be able to watch them in the same sequence as original Youtube playlist. In other words I need my downloaded videos to be prefixed with numbers. How can I do that?

**Comment by insaneracist** [comment] 2020-11-10 09:24
@candrapersada, check out the readme section called [output template](https://github.com/blackjack4494/yt-dlc/blob/master/README.md#output-template)
if playlist downloading isn't broken, you can do
`youtube-dlc -o "%(playlist_index)03d - %(title)s.%(ext)s" "https://www.youtube.com/playlist?list=..."`

**Comment by arter97** [comment] 2020-11-10 12:11
Hm, the playlist's title is still missing from these fixes @ZenulAbidin @insaneracist 

Similar to #109.

```
python3.9 ./__main__.py --flat-playlist --add-metadata --all-subs -J -F 'https://youtube.com/playlist?list=PLq-W-cmkohAPAcxZWxh_ysJWPhqDxkETs'
```
Doesn't return a valid title key.

**Comment by insaneracist** [comment] 2020-11-10 12:42
@arter97 fixed

**Comment by blackjack4494** [comment] 2020-11-10 12:47
Expect a release with a patch for this coming today (anything between 1-10 hrs depending on when I got time). Python version will be fixed then as well as win xp support is back then.

**Comment by ZenulAbidin** [comment] 2020-11-10 19:20
I was booked today, now that I have some free time I’ll see where in the JSON our variables have moved to and hopefully find a regex to match them.

**Closed** 2020-11-10 23:05 UTC

**Comment by blackjack4494** [comment] 2020-11-10 23:32
That's unfortunate
https://github.com/actions/upload-release-asset/issues/68

Release is delayed till this issue is fixed.

**Comment by perry-mitchell** [comment] 2020-11-11 12:46
@blackjack4494 Seems that the linked issue is [fixed](https://github.com/actions/upload-release-asset/issues/68#issuecomment-725234607), according to comments. Would you have a potential ETA on release? Thank you :pray:

**Comment by candrapersada** [comment] 2020-11-11 17:16
why name folder broken `%(playlist)s/`?

**Comment by harrypotter0** [comment] 2020-11-12 02:16
Hi everyone. I am trying to use this command to download playlist but not able to do so since past 2-3 days. Till now I can't see any fix for this. If anyone can tell me how to go past this issue it would be great help.
```
youtube-dl -c -i -f 18  https://www.youtube.com/playlist?list=PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt
[youtube:playlist] PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt: Downloading webpage
[download] Downloading playlist: PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt
[youtube:playlist] playlist PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt: Downloading 0 videos
[download] Finished downloading playlist: PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt
```

**Comment by Fabian42** [comment] 2020-11-12 07:58
@harrypotter0 Which system are you using? For Manjaro Linux, a package update was available when I checked 9 hours ago, since then it works again. Some other distributions might take longer. Debian for example sometimes takes months, so you might want to download it from Github and install it that way instead.

**Comment by someziggyman** [comment] 2020-11-12 08:12
> Hi everyone. I am trying to use this command to download playlist but not able to do so since past 2-3 days. Till now I can't see any fix for this. If anyone can tell me how to go past this issue it would be great help.
> 
> ```
> youtube-dl -c -i -f 18  https://www.youtube.com/playlist?list=PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt
> [youtube:playlist] PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt: Downloading webpage
> [download] Downloading playlist: PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt
> [youtube:playlist] playlist PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt: Downloading 0 videos
> [download] Finished downloading playlist: PLv_5Gzr5T6wz0G1Ff3SO97ElLq1G0POWt
> ```
This particular playlist is working on the latest release.
try also using --rm-cache-dir --no-cache-dir params in your command.

**Comment by cgerrie** [comment] 2020-11-13 07:50
When I download my Youtube watch later playlist, it only downloads the first page. Any videos beyond the first 100 don't get downloaded. This happens using both `youtube-dlc --cookies cookies.txt :ytwatchlater` and `youtube-dlc --cookies cookies.txt https://www.youtube.com/playlist?list=WL`. I am using version 2020.11.11-3, and I've cleared my cache directory. I've tried messing with the `--playlist-start` and `--playlist-end` flags, but those don't seem to help either. Could this be because the watch later playlist has some unique polymer structure that got missed in the patch?

**Comment by heywolf15** [comment] 2020-11-16 00:54
> 
> 
> When I download my Youtube watch later playlist, it only downloads the first page. Any videos beyond the first 100 don't get downloaded. This happens using both `youtube-dlc --cookies cookies.txt :ytwatchlater` and `youtube-dlc --cookies cookies.txt https://www.youtube.com/playlist?list=WL`. I am using version 2020.11.11-3, and I've cleared my cache directory. I've tried messing with the `--playlist-start` and `--playlist-end` flags, but those don't seem to help either. Could this be because the watch later playlist has some unique polymer structure that got missed in the patch?

The same happen to me.  When the version 2020.11.11-3 came out, it fixes it. Now it broke again

**Comment by heywolf15** [comment] 2020-11-16 01:01
> 
> This particular playlist is working on the latest release.
> try also using --rm-cache-dir --no-cache-dir params in your command.

Can confirm that this works, nice

**Comment by theAkito** [comment] 2020-12-02 17:00
I updated to today's youtube-dl version through pip. Still, none of the auxiliary options like `--rm-cache-dir --no-cache-dir` seem to work. Tried to download several completely different channels' videos and yet, it always tells me, that there are only 0 videos to download, which is absolutely false.

What am I missing here? Is this truly fixed?

**Comment by blackjack4494** [comment] 2020-12-02 17:07
Try updating to master with git. Search for git in readme :)
