### ISSUE TITLE
64-bit .EXE depends on "api-ms-win-core-path-l1-1-0 dll"

### ISSUE THREAD

**Issue by filler56789** [blackjack4494/yt-dlc#78] opened 2020-10-31 09:51 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Pop-up message:
«The program can't start because "api-ms-win-core-path-l1-1-0 dll" is missing from your computer.»
Command-prompt message:
«Error loading Python DLL 'C:\TEMP-D~1\New-TMP\_MEI40802\python39.dll'.
LoadLibrary: The specified module could not be found.»

On the other hand, the 32-bit executable works normally under the 64-bit Windows 7.

**Comment by userlip** [comment] 2020-10-31 12:29
duplicate of #77

**Closed** 2020-11-01 02:44 UTC
