### ISSUE TITLE
"error loading python dll"

### ISSUE THREAD

**Issue by chrisr11** [blackjack4494/yt-dlc#114] opened 2020-11-04 02:59 UTC
## Checklist

- [] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

Hi, why doesn't the Windows binary have Python embedded in it just like how youtube-dl did? I have installed youtube-dlc on my work computer and it throws an error stating: error loading python dll 'c:\users\chris\appdata\local\temp\_mei42642\python39.dll'.

I can't make changes on my work computer due to restrictions but shouldn't the binary have python embedded in it similar to how youtube-dl did? In fact, I installed the latest youtube-dl binary and that worked fine with no issues.

Please help, thanks!

**Comment by SeonjaeHyeon** [comment] 2020-11-04 03:54
duplicate of #77

**Comment by chrisr11** [comment] 2020-11-04 13:34
So how can I bundle Python in the binary? Like how youtube-dl does it

**Comment by blackjack4494** [comment] 2020-11-04 17:21
Read readme.

**Comment by chrisr11** [comment] 2020-11-05 01:57
This?

![image](https://user-images.githubusercontent.com/73445815/98188019-3d024a80-1ee0-11eb-8b64-bcd4f29f3a0a.png)

I did exactly this and the binary threw the Python missing error on Windows 7

**Comment by blackjack4494** [comment] 2020-12-02 01:10
should be fixed.

**Closed by blackjack4494** 2020-12-02 01:10 UTC
