### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll miss

### ISSUE THREAD

**Issue by ircopdd** [blackjack4494/yt-dlc#139] opened 2020-11-08 09:34 UTC
please support win7 x64

**Comment by bitraid** [comment] 2020-11-08 21:38
Install [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows)

**Comment by mjb2010** [comment] 2020-11-09 05:42
KB2999226 already installed. It does not help. That DLL is apparently only for Win8 and up.

**Comment by bitraid** [comment] 2020-11-09 12:05
Try installing [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by Vangelis66** [comment] 2020-11-09 19:06
@bitraid : As pointed out **already**, the missing dll (either 32/64-bit) is an integral part of **Win8+** OSes and can't be installed on EoL'ed Win7 by a standalone MS update/redistributable... Please kindly research your proposed "_solutions_"; it's simple: Python 3.**9** does NOT support Win7, period... To re-instate Win7 support, the project has to use Python 3.8.6 (or earlier) 64-bit to compile the 64-bit youtube-dlc provided binary!

This is in fact one more duplicate of https://github.com/blackjack4494/yt-dlc/issues/114, https://github.com/blackjack4494/yt-dlc/issues/77, https://github.com/blackjack4494/yt-dlc/issues/78.

In the interim, just use the 32-bit binary, **youtube-dlc_x86.exe** (compiled with Python **3.5.4**) ... You know, people still use **32-bit** OSes (and 32-bit executables **do run on 64-bit** ones...).

**Comment by blackjack4494** [comment] 2020-11-09 20:26
I simply forgot to change the python version for Windows as well. Linux is already back on 3.8
As for 32 bit version it will support xp soon again. 3.4.4 is available now as 32 bit version.

**Closed** 2020-11-10 23:16 UTC
